/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taprakdkp;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Set;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;


public class TiketBus extends javax.swing.JFrame {

    private Set<String> kursiTerpesan;
    private Map<String, Integer> hargaDestinasi;
    
    public TiketBus() {
        kursiTerpesan = new HashSet<>();
        hargaDestinasi = new HashMap<>();
        initHargaDestinasi();
        initComponents();
        initializeSeatButtons();
        setSize(600, 600);
        setTitle("Bus Ticketing System");


    }
    
private void initHargaDestinasi() {
        hargaDestinasi.put("Surabaya", 200000);
        hargaDestinasi.put("Jogjakarta", 120000);
        hargaDestinasi.put("Cirebon", 375000);
}

private int getHargaUntukDestinasi(String destinasi) {
        return hargaDestinasi.get(destinasi);
    }

private void initializeSeatButtons() {
    // Panel untuk kursi di bagian kiri atas
    JPanel leftTopPanel = new JPanel(new GridLayout(11, 2, 5, 10));
    for (int i = 1; i <= 22; i++) {
        String seatNumber = "Kursi " + i;
        JButton seatButton = createSeatButton(seatNumber);
        leftTopPanel.add(seatButton);
    }
    
    // Panel untuk kursi di bagian kanan atas
    JPanel rightTopPanel = new JPanel(new GridLayout(11, 2, 5, 10));
    for (int i = 23; i <= 44; i++) {
        String seatNumber = "Kursi " + i;
        JButton seatButton = createSeatButton(seatNumber);
        rightTopPanel.add(seatButton);
    }

    // Panel untuk kursi di bagian bawah
    JPanel bottomPanel = new JPanel(new GridLayout(1, 5, 5, 10));
    for (int i = 45; i <= 49; i++) {
        String seatNumber = "Kursi " + i;
        JButton seatButton = createSeatButton(seatNumber);
        bottomPanel.add(seatButton);
    }

    // Tambahkan panel-panel ke dalam panel utama
    jPanel1.setLayout(new BorderLayout());
    jPanel1.add(leftTopPanel, BorderLayout.WEST);
    jPanel1.add(rightTopPanel, BorderLayout.EAST);
    jPanel1.add(bottomPanel, BorderLayout.SOUTH);
}

private JButton createSeatButton(String seatNumber) {
    JButton seatButton = new JButton(seatNumber);
    seatButton.setBackground(Color.GREEN);
    seatButton.addActionListener(new SeatButtonListener(seatNumber, seatButton));
    return seatButton;
}


    private class SeatButtonListener implements ActionListener {
        private String seatNumber;
        private JButton seatButton;

        public SeatButtonListener(String seatNumber, JButton seatButton) {
            this.seatNumber = seatNumber;
            this.seatButton = seatButton;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            if (kursiTerpesan.contains(seatNumber)) {
                kursiTerpesan.remove(seatNumber);
                seatButton.setBackground(Color.GREEN);
            } else {
                int JumlahTiket = (int) jSpinner1.getValue();
                if (kursiTerpesan.size() < JumlahTiket) {
                    kursiTerpesan.add(seatNumber);
                    seatButton.setBackground(Color.RED);
                } else {
                    JOptionPane.showMessageDialog(null, "Jumlah kursi sudah sesuai dengan jumlah tiket", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Destinasi");

        jLabel3.setText("Jumlah Tiket");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surabaya - Rp200.000", "Jogjakarta - Rp230.000", "Cirebon - Rp375.000" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Pesan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nama = jTextField1.getText();
        String destinasi = (String) jComboBox1.getSelectedItem();
        int JumlahTiket = (int) jSpinner1.getValue();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan nama anda", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (JumlahTiket > kursiTerpesan.size()) {
            JOptionPane.showMessageDialog(null, "Tolong pilih " + JumlahTiket + " kursi", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int Hargatotal = getHargaUntukDestinasi(destinasi) * JumlahTiket; // Hitung total harga
            String ticketInfo = "Nama: " + nama + "\nDestinasi: " + destinasi + "\nJumlah Tiket: " + JumlahTiket + "\nHarga Total: Rp" + Hargatotal + "\nNomor Kursi: " + kursiTerpesan + "\n\n";
            jTextArea1.append(ticketInfo);
            jTextField1.setText("");
            jSpinner1.setValue(1);
            kursiTerpesan.clear();
            resetSeatButtons();
            JOptionPane.showMessageDialog(this, "Pesanan telah berhasil dikirim!", "Konfirmasi", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void resetSeatButtons() {
        Component[] components = jPanel1.getComponents();
        for (Component component : components) {
            if (component instanceof JButton) {
                component.setBackground(Color.GREEN);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiketBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
